### ISSUE TITLE
There is a question

### ISSUE THREAD

**Issue by pjc12345678** [Kohulan/DECIMER-Image-Segmentation#102]
Thank you for your code,  I have a question that in your web I can get the Resolved SMILES representation and picture which can be modified, but I can't find relative code in this project, Is the relative code open source ?

**Comment by Kohulan** [comment]
Hi @pjc12345678 ,

The modified molecule image is generated using the Ketcher software, which is openly available as open-source. You can find it here: https://lifescience.opensource.epam.com/ketcher/index.html

- Kohulan

**Comment by pjc12345678** [comment]
Thank you for you reply, I still have some doubts, Is the code which produces SMILES in this repo?

**Comment by Kohulan** [comment]
Hi @pjc12345678 ,

The Image to SMILES code is here: https://github.com/Kohulan/DECIMER-Image_Transformer
Please check our paper for more information: https://www.nature.com/articles/s41467-023-40782-0

- Kohulan
