### ISSUE TITLE
My program got killed 

### ISSUE THREAD

**Issue by shivanandakandagalla** [Kohulan/DECIMER-Image-Segmentation#106]
I am working on image segmentation for a couple of PDF files. Before executing the code below, I split the PDF into individual files based on page numbers. However, during the execution of the code, the process gets terminated after processing the seventh file.

     for file in files:
        file_path = os.path.join(output_folder_path, file)
        #print(file_path)
        pages = convert_from_path(file_path, 300)
        raw_segments = segment_chemical_structures(np.array(pages[0], expand=True, visualization=False) 
        save_images(raw_segments, output_folder_path, name=f"{file[:-4]}")

**Comment by Kohulan** [comment]
Hi @shivanandakandagalla ,

This could be an issue with the memory. Without access to error logs, our ability to assist you is limited.

**Comment by OBrink** [comment]
Closed until more information is provided (@shivanandakandagalla )
