### ISSUE TITLE
Issues with mrcnn parallel model

### ISSUE THREAD

**Issue by cmc227** [Kohulan/DECIMER-Image-Segmentation#109]
Hi,

When running across multiple gpus, I get `ModuleNotFoundError` from `mrcnn.parallel_model import ParallelModel` in model.py.

I add the parallel model from https://github.com/matterport/Mask_RCNN but then get the error `'ParallelModel' object has no attribute '_base_model_initialized'`

Would anyone be able to help with this?

Thanks

**Comment by Kohulan** [comment]
Hi @cmc227 ,

I will try to look into this. Since it is Mask RCNN issue I think it is due to TF 2.0. The original Mask RCNN was written using TF 1.0.
