### ISSUE TITLE
Expand is too big. What can I modify？

### ISSUE THREAD

**Issue by rookiexiao123** [Kohulan/DECIMER-Image-Segmentation#31]
![image](https://user-images.githubusercontent.com/32377884/132628102-371d3970-2060-4ac4-a9af-e091bb483d54.png)

**Comment by OBrink** [comment]
In the dilated image, the complete scaffold of the table is one connected object. The way to go here would be to work without the expansion

**Comment by OBrink** [comment]
@rookiexiao123, sorry for the late resolution of the problem, but this issue has been fixed in version 1.3.0
