### ISSUE TITLE
Including molecule label in an output image

### ISSUE THREAD

**Issue by willfinnigan** [Kohulan/DECIMER-Image-Segmentation#33]
Hi,

Awesome package!  I was wondering, is there any easy way to include a third image in the output which maybe includes a slightly expanded area around a molecule, to try and  include the label for the molecule.  

For example, many of the papers I'm dealing with will include a figure showing a panel of substrates, each one given a number or letter.  I'd like to use DECIMER to do segment the molecules, use OSRA to do image recognition on each segmented molecules, and then also include the source image so that a human user can go through and label the molecules / SMILES appropriately.  This is of course possible just from the original PDF, but it can be a little time consuming matching the OSRA output to the original molecule label in each case.

Thanks!

Will

**Comment by willfinnigan** [comment]
Here's an example of what I mean
<img width="412" alt="Screenshot 2021-11-09 at 15 55 49" src="https://user-images.githubusercontent.com/15628614/140958569-be78604f-7961-40c3-b3f8-acf8fa2923dd.png">

**Comment by Kohulan** [comment]
Hi @willfinnigan ,

There are two things you could do,
1. Retrain the Mask-RCNN model with examples as such you have shown. So you could create masks with molecules and their labels.
2. Try to modify the Mask Expansion algorithm to include the labels. But the mask expansion algorithm works with pixel values so it might end up trapping a lot of unwanted artefacts as well.

-Kohulan
