### ISSUE TITLE
How do I train the model with my own data and moldetect.py ？

### ISSUE THREAD

**Issue by stud2008** [Kohulan/DECIMER-Image-Segmentation#36]
Hi, I'm very interested in this project. I tried to train a new model starting from pre-trained mask_rcnn_molecule.h5 weights. And then there are some difficulties here. 
1. Use moldetect.py with mask_rcnn_molecule.h5 weights, start training with the following command and then encounter an error.
```
python mrcnn/moldetect.py train --dataset=/path/to/train_data/  --weights=/path/to/mask_rcnn_molecule.h5
```

error message:

> Traceback (most recent call last):
>   File "./mrcnn/moldetect.py", line 366, in <module>
>     model.load_weights(weights_path, by_name=True) 
>   File "/DECIMER-Image-Segmentation-master/mrcnn/model.py", line 2140, in load_weights
>     hdf5_format.load_weights_from_hdf5_group_by_name(f, layers)
>   File "/miniconda3/envs/tf23/lib/python3.8/site-packages/tensorflow/python/keras/saving/hdf5_format.py", line > 767, in load_weights_from_hdf5_group_by_name
>     raise ValueError('Layer #' + str(k) + ' (named "' + layer.name +
> ValueError: Layer #362 (named "anchors") expects 1 weight(s), but the saved weights have 0 element(s).

2.Use moldetect.py with mask_rcnn_balloon.h5 weights(from matterport/Mask_RCNN), No bugs were shown up, but the program stalled on the first epoch for a long time. I waited for 3 hours and it didn't progress.

I would like someone to write instructions for the moldetect.py script for model training, thank you very much.

**Comment by Kohulan** [comment]
Hello @stud2008 ,

This model was trained on only one object, so when you want to include more than one object, it will fail to retrain. 

I suggest that you retrain your model using your own annotations. To retrain your own model, please follow the [tutorial](https://engineering.matterport.com/splash-of-color-instance-segmentation-with-mask-r-cnn-and-tensorflow-7c761e238b46?gi=afd78bfe1a71) provided by the Matterport team.

-Kohulan
