### ISSUE TITLE
Dataset issues

### ISSUE THREAD

**Issue by Sbboss** [Kohulan/DECIMER-Image-Segmentation#55]
Hi, i am a student really fascinated about CV and want to train ny own model on the same problem. Because of no man power i can't annotations the segmentation by myself.
 Can you please kindly provide Dataset link please

**Comment by OBrink** [comment]
I am sorry, but unfortunately, we cannot provide the dataset as this would be a copyright infringement. We manually annotated structures in the Journal of Natural Products and used these annotated regions as training data. Publishing the data would mean publishing the articles which we cannot do.
