### ISSUE TITLE
Could not load dynamic library 'libcudart.so.11.0'

### ISSUE THREAD

**Issue by Iagea** [Kohulan/DECIMER-Image-Segmentation#62]
Hi,

can you provide the CUDA version that you are using and the drivers version as well? It gets suck while using CUDA 11.7.

Have a nice day,
Isa.

**Comment by Kohulan** [comment]
Do you want to train the model? or use it? 
The whole algorithm works just on CPUs and you do not need any CUDA drivers.

According to the title it is mostly the libcuda.so.11 is not getting appropriately loaded probably you might have to reinstall it.

**Comment by Iagea** [comment]
Use it, the problem is that if I use it on a machine without GPUs it works but if there are GPUs available, it shows the error and gets stuck after several warning messages like this one:

`2022-12-09 15:04:01.109440: W tensorflow/core/grappler/costs/op_level_cost_estimator.cc:690] Error in PredictCost() for the op: op: "CropAndResize" attr { key: "T" value { type: DT_FLOAT } } attr { key: "extrapolation_value" value { f: 0 } } attr { key: "method" value { s: "bilinear" } } inputs { dtype: DT_FLOAT shape { dim { size: -45 } dim { size: 32 } dim { size: 32 } dim { size: 256 } } } inputs { dtype: DT_FLOAT shape { dim { size: -40 } dim { size: 4 } } } inputs { dtype: DT_INT32 shape { dim { size: -40 } } } inputs { dtype: DT_INT32 shape { dim { size: 2 } } value { dtype: DT_INT32 tensor_shape { dim { size: 2 } } int_val: 14 } } device { type: "CPU" vendor: "GenuineIntel" model: "111" frequency: 2600 num_cores: 16 environment { key: "cpu_instruction_set" value: "AVX SSE, SSE2, SSE3, SSSE3, SSE4.1, SSE4.2" } environment { key: "eigen" value: "3.4.90" } l1_cache_size: 32768 l2_cache_size: 262144 l3_cache_size: 36700160 memory_size: 268435456 } outputs { dtype: DT_FLOAT shape { dim { size: -40 } dim { size: 14 } dim { size: 14 } dim { size: 256 } } }`

**Comment by Kohulan** [comment]
If you want to use it with GPU then under mrcnn/model.py

change the value of os.environ["CUDA_VISIBLE_DEVICES"] = "3" to os.environ["CUDA_VISIBLE_DEVICES"] = "0"
