### ISSUE TITLE
Deprecated datatypes/args on new install of 1.1.1

### ISSUE THREAD

**Issue by adhardydm** [Kohulan/DECIMER-Image-Segmentation#65]
Hi Guys,

I've had problems with a fresh install of 1.1.1 from pip.

1. Numpy (1.24.2) deprecated np.bool in 1.20 and this is used in several places within the project source. Downgrading numpy to 1.19.5 caused problems with the version of tensorflow I was pulling ("...compiled for different version of numpy...") but changing all instances of `np.bool` to `bool` in the source seems to fix it.

2. The `binary_erosion` function from `skimage.morphology` uses the `selem` kwarg which looks like it was changed to `footprint` at some point and was not working with the version of skimage that was installed (0.20.0). Replacing the `selem` arg with `footprint` seems to work.

Happy to create a pull request with these fixes, unless there is another way you'd want to approach it - either way looks like you need to tighten up your version requirements.

**Comment by Kohulan** [comment]
@adhardydm ,

Thank you for the update. The DECIMER and its sub-modules are currently working on Linux-based machines, which is also our top priority. We are happy to review a pull request if you confirm that the changes you make are compatible with Linux.

**Comment by adhardydm** [comment]
I have the same issues on Linux - will pop up a PR and can disuss more there.

**Comment by adhardydm** [comment]
Resolved by #66
