### ISSUE TITLE
Cannot install DECIMER transformer and segmenter in same environment: tensorflow version different

### ISSUE THREAD

**Issue by adhardydm** [Kohulan/DECIMER-Image-Segmentation#67]
https://github.com/Kohulan/DECIMER-Image_Transformer requires tensorflow 2.10.0 and segmenter requires 2.10.1 - they will not install in the same environment.

**Comment by Kohulan** [comment]
@adhardydm Thanks a lot. Currently, I made the changes in setup.py. I will update the PyPI package once I confirm it is working as we intend.
